version: '3'
services:
  holidayDessert-server:
    image: ghcr.io/anthonyfufu/holidaydessert:latest
    ports:
      - 8080:8080
    networks:
      - holidayDessert-bridge
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldbcompose:3306/holiday_dessert?serverTimezone=Asia/Taipei
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_DATA_REDIS_HOST=redisdbcompose
      - SPRING_DATA_REDIS_PORT=6379
    depends_on:
      - mysqldbcompose
      - redisdbcompose
  mysqldbcompose:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'holiday_dessert'
      MYSQL_ROOT_PASSWORD: '123456'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./holiday_dessert分大小寫.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - holidayDessert-bridge
  redisdbcompose:
    image: redis:7
    ports:
      - '6379:6379'
    networks:
      - holidayDessert-bridge
networks:
  holidayDessert-bridge:
volumes:
  mysql-data:
