version: '3'
services:
  forecast-server:
    build: .
    ports:
      - 8080:8050
    networks:
      - forecast-bridge
    environment:
      - spring.datasource.druid.first.url=jdbc:mysql://mysqldbcompose:3306/forecast
      - spring.datasource.druid.first.username=root
      - spring.datasource.druid.first.password=tkb0004757
      - spring.datasource.druid.first.driver-class-name =com.mysql.cj.jdbc.Driver
    depends_on:
      - mysqldbcompose
  mysqldbcompose:
    image: mariadb:10.5.3
    ports:
      - '3307:3306'
    environment:
      MYSQL_DATABASE: 'forecast'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'tkb0004757'
      MYSQL_ROOT_PASSWORD: 'tkb0004757'
    volumes:
      - /app/server/mysql:/var/lib/mysql
    networks:
      - forecast-bridge
networks:
  forecast-bridge:
    external: true