CREATE DATABASE IF NOT EXISTS holiday_dessert;
USE holiday_dessert;

DROP TABLE IF EXISTS product_pic;
DROP TABLE IF EXISTS message;
DROP TABLE IF EXISTS chat_room;
DROP TABLE IF EXISTS promotion_detail;
DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS product_collection;
DROP TABLE IF EXISTS member_coupon;
DROP TABLE IF EXISTS promotion;
DROP TABLE IF EXISTS coupon;
DROP TABLE IF EXISTS main_order;
DROP TABLE IF EXISTS cart;
DROP TABLE IF EXISTS receipt_information;
DROP TABLE IF EXISTS member;
DROP TABLE IF EXISTS authority;
DROP TABLE IF EXISTS emp_function;
DROP TABLE IF EXISTS employee;
DROP TABLE IF EXISTS department;
DROP TABLE IF EXISTS banner;
DROP TABLE IF EXISTS news;
DROP TABLE IF EXISTS company_information;
DROP TABLE IF EXISTS order_detail;
DROP TABLE IF EXISTS fullcalendar;
DROP TABLE IF EXISTS ticket_event;
DROP TABLE IF EXISTS ticket_type;
DROP TABLE IF EXISTS ticket_order;
-- ================== CREATE TABLE(會員）================== --

CREATE TABLE `member`(
MEM_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '會員ID',
MEM_NAME VARCHAR(45) NOT NULL COMMENT '姓名',
MEM_ACCOUNT VARCHAR(50) NOT NULL COMMENT '帳號',
MEM_PASSWORD VARCHAR(20) NOT NULL COMMENT '密碼',
MEM_GENDER CHAR(1) COMMENT '性別(f:女 m:男)',
MEM_PHONE VARCHAR(20) COMMENT '電話',
MEM_EMAIL VARCHAR(50) NOT NULL COMMENT '信箱',
MEM_ADDRESS VARCHAR(100) COMMENT '地址',
MEM_BIRTHDAY DATE COMMENT '生日',
MEM_PICTURE VARCHAR(300) COMMENT '會員圖片路徑',
MEM_IMAGE VARCHAR(100) COMMENT '會員圖片名稱',
MEM_STATUS INT(1) DEFAULT(1) COMMENT '會員狀態(1:正常 0:停權)',
MEM_VERIFICATION_STATUS INT(1) DEFAULT(1) COMMENT '會員驗證狀態(1:開通 0:停權)',
MEM_VERIFICATION_CODE VARCHAR(100) COMMENT '會員驗證碼',
MEM_GOOGLE_UID VARCHAR(100) COMMENT '會員googleUid',
CONSTRAINT unikey_MEM_ACCOUNT UNIQUE(MEM_ACCOUNT)
) COMMENT='會員';
INSERT INTO `member`(MEM_NAME, MEM_ACCOUNT, MEM_PASSWORD, MEM_GENDER, MEM_PHONE, MEM_EMAIL,MEM_ADDRESS, MEM_BIRTHDAY,MEM_STATUS,MEM_VERIFICATION_STATUS,MEM_GOOGLE_UID)
VALUES  ('傅勝宏', 'FU830917', '830917', 'm', '0999000000','s9017611@gmail.com','台北市中正區博愛路36號',STR_TO_DATE('1994-09-17','%Y-%m-%d'),1,1,NULL),
		('阿勝', 'ASHENG', '830917', 'f', '0988000000','s9017611@gmail.com','台北市中正區博愛路36號',STR_TO_DATE('1994-09-17','%Y-%m-%d'),1,1,NULL),
        ('傅', 'FU30917', '830917', 'm', '0999000000','s9017611@gmail.com','台北市中正區博愛路36號',STR_TO_DATE('1994-09-17','%Y-%m-%d'),1,1,NULL),
        ('勝', 'FU83917', '830917', 'm', '0999000000','s9017611@gmail.com','台北市中正區博愛路36號',STR_TO_DATE('1994-09-17','%Y-%m-%d'),1,1,NULL),
        ('宏', 'FU83097', '830917', 'm', '0999000000','s9017611@gmail.com','台北市中正區博愛路36號',STR_TO_DATE('1994-09-17','%Y-%m-%d'),1,1,NULL)
        ;

-- 常用收貨資訊 --
CREATE TABLE receipt_information(
RCP_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '常用收貨資訊ID',
MEM_ID INT NOT NULL COMMENT '會員ID',
RCP_NAME VARCHAR(45) NOT NULL COMMENT '收貨者姓名',
RCP_CVS VARCHAR(255) COMMENT '超商收貨地址',
RCP_ADDRESS VARCHAR(255) COMMENT '收件人地址',
RCP_PHONE VARCHAR(20) NOT NULL COMMENT '收件人聯絡電話',
CONSTRAINT receipt_information_member_fk FOREIGN KEY (MEM_ID) REFERENCES member(MEM_ID)
) COMMENT='常用收貨資訊';
INSERT INTO receipt_information(MEM_ID,RCP_NAME,RCP_CVS,RCP_PHONE)
VALUES ('1','傅勝宏','全家中壢中山店','0999000000');

-- ================== CREATE TABLE(管理員相關）================== --

-- 部門 --
CREATE TABLE department(
DEPT_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '部門ID',
DEPT_NAME VARCHAR(30) NOT NULL COMMENT '部門名稱',
DEPT_LOC VARCHAR(100) COMMENT '部門地點'
) COMMENT='部門';
INSERT INTO department(DEPT_NAME, DEPT_LOC)
VALUES  ('資訊部', '桃園市'),
		('業務部', '桃園市');

-- 管理員 --
CREATE TABLE employee(
EMP_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '管理員ID',
DEPT_ID INT(10) COMMENT '部門ID',
EMP_NAME VARCHAR(20) NOT NULL COMMENT '姓名',
EMP_PHONE VARCHAR(20) NOT NULL COMMENT '電話',
EMP_JOB VARCHAR(30) NOT NULL COMMENT '職稱',
EMP_SALARY INT(10) NOT NULL COMMENT '薪水',
EMP_PICTURE VARCHAR(300) COMMENT '照片路徑',
EMP_IMAGE VARCHAR(100) COMMENT '照片名稱',
EMP_ACCOUNT VARCHAR(20) NOT NULL COMMENT '帳號',
EMP_PASSWORD VARCHAR(20) NOT NULL COMMENT '密碼',
EMP_EMAIL VARCHAR(40) NOT NULL COMMENT '信箱',
EMP_LEVEL INT(2) NOT NULL COMMENT '等級(0:最高管理員 1:一般管理員)',
EMP_MANAGER_ID INT DEFAULT NULL COMMENT '管理者ID',
EMP_STATUS INT(1) NOT NULL DEFAULT '1' COMMENT '狀態(0:停權 1:啟用)',
EMP_HIREDATE DATE NOT NULL DEFAULT (CURRENT_DATE) COMMENT '入職日',
EMP_THEME VARCHAR(40) COMMENT '主題',
CONSTRAINT unikey_EMP_ACCOUNT UNIQUE(EMP_ACCOUNT),
CONSTRAINT employee_department_fk FOREIGN KEY (DEPT_ID) REFERENCES department(DEPT_ID),
CONSTRAINT employee_manager_fk FOREIGN KEY (EMP_MANAGER_ID) REFERENCES employee(EMP_ID) ON DELETE SET NULL
) COMMENT='管理員';
INSERT INTO employee(EMP_NAME, DEPT_ID, EMP_PHONE, EMP_JOB, EMP_SALARY, EMP_PICTURE, EMP_IMAGE, EMP_ACCOUNT, EMP_PASSWORD, EMP_EMAIL, EMP_LEVEL, EMP_STATUS,EMP_MANAGER_ID) 
VALUES  ('傅勝宏', '1', '0912345678', '軟體工程師', '46250','holidayDessert/admin/upload/images/employee/user.jpg','user.jpg','holidaydessert101', 'emppassword1','s9017688@yahoo.com.tw','0','1',null),
		('AnthonyFu', '2', '0987654321', '行銷+美編', '31500','holidayDessert/admin/upload/images/employee/user.jpg','user.jpg','holidaydessert102', 'emppassword2','s9017611@gmail.com','0','1',1),
		('AnthonyFu2', '2', '0987654321', '行銷+美編', '31500','holidayDessert/admin/upload/images/employee/user.jpg','user.jpg','holidaydessert103', 'emppassword3','s9017622@gmail.com','0','1',1);
        
-- 功能-- 
CREATE TABLE emp_function(
FUNC_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '功能ID',
FUNC_NAME VARCHAR(40) NOT NULL COMMENT '功能名稱',
FUNC_LAYER VARCHAR(5) COMMENT '功能層級',
FUNC_PARENT_ID VARCHAR(5) COMMENT '功能隸屬',
FUNC_LINK VARCHAR(100) COMMENT '功能連結',
FUNC_STATUS INT(1) NOT NULL DEFAULT '1' COMMENT '功能狀態',
FUNC_ICON VARCHAR(50) COMMENT 'ICON'
) COMMENT='功能';
INSERT INTO emp_function(FUNC_NAME,FUNC_LAYER,FUNC_PARENT_ID,FUNC_LINK,FUNC_STATUS,FUNC_ICON)
VALUES ('公司管理','1','0','/holidayDessert/admin/company/list',1,'business'),
	('員工管理','1','0','/holidayDessert/admin/employee/list',1,'group_add'),
	('排班管理','1','0','/holidayDessert/admin/calendar/list',1,'date_range'),
	('會員管理','1','0','/holidayDessert/admin/member/list',1,'people'),
	('訂單管理','1','0','/holidayDessert/admin/order/list',1,'payment'),
	('商品管理','1','0','/holidayDessert/admin/product/list',1,'shop'),
	('優惠活動管理','1','0','/holidayDessert/admin/promotion/list',1,'event'),
	('優惠券管理','1','0','/holidayDessert/admin/coupon/list',1,'card_giftcard'),
	('最新消息管理','1','0','/holidayDessert/admin/news/list',1,'fiber_new');

-- 管理員權限 --
CREATE TABLE authority(
EMP_ID INT NOT NULL COMMENT '管理員ID',
FUNC_ID INT NOT NULL COMMENT '功能ID',
AUTH_STATUS INT(1) NOT NULL DEFAULT '1' COMMENT '權限狀態',
CONSTRAINT authority_employee_FK FOREIGN KEY (EMP_ID) REFERENCES employee(EMP_ID),
CONSTRAINT authority_emp_function_FK FOREIGN KEY (FUNC_ID) REFERENCES emp_function(FUNC_ID), 
CONSTRAINT PK_authority_emp_ID_FUNC_ID PRIMARY KEY (EMP_ID, FUNC_ID)
) COMMENT='管理員權限';
INSERT INTO authority(EMP_ID, FUNC_ID, AUTH_STATUS)
VALUES  (1,1,1),(1,2,1),(1,3,1),(1,4,1),(1,5,1),(1,6,1),(1,7,1),(1,8,1),(1,9,1),
        (2,1,0),(2,2,0),(2,3,1),(2,4,1),(2,5,1),(2,6,1),(2,7,1),(2,8,1),(2,9,1),
        (3,1,1),(3,2,1),(3,3,1),(3,4,1),(3,5,1),(3,6,1),(3,7,1),(3,8,1),(3,9,1);

-- 最新消息 --
CREATE TABLE news(
NEWS_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '最新消息ID',
PM_ID INT COMMENT '活動優惠ID',
NEWS_NAME VARCHAR(50) COMMENT '最新消息名稱',
NEWS_CONTENT VARCHAR(500) COMMENT '最新消息內容',
NEWS_STATUS INT(1) NOT NULL DEFAULT '1' COMMENT '最新消息狀態(0:下架 1:上架 Default:0)',
NEWS_START DATETIME COMMENT '開始時間',
NEWS_END DATETIME COMMENT '結束時間',
NEWS_CREATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) COMMENT='最新消息';
INSERT INTO news(PM_ID,NEWS_ID,NEWS_NAME,NEWS_CONTENT,NEWS_START,NEWS_END)
VALUES (null,'1','慶祝父親節','慶祝父親節，全館88折',CONCAT(CURDATE(), ' 00:00:00'),CONCAT(DATE_ADD(CURDATE(), INTERVAL 1 WEEK), ' 23:59:59')),
	   (2,'2','歡慶中元節','歡慶中元節，全館9折',CONCAT(CURDATE(), ' 00:00:00'),CONCAT(DATE_ADD(CURDATE(), INTERVAL 1 WEEK), ' 23:59:59')),
       (null,'3','中秋節快樂','中秋節快樂，全館79折',CONCAT(CURDATE(), ' 00:00:00'),CONCAT(DATE_ADD(CURDATE(), INTERVAL 1 WEEK), ' 23:59:59'));

-- BANNER --
CREATE TABLE banner(
BAN_ID	INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '公告BannerID',
NEWS_ID	 int NOT NULL COMMENT '最新消息ID',
BAN_PICTURE VARCHAR(300) COMMENT '公告Banner圖片路徑',
BAN_IMAGE VARCHAR(100) COMMENT '公告Banner圖片名稱',
CONSTRAINT banner_news_FK FOREIGN KEY (NEWS_ID) REFERENCES news(NEWS_ID)
) COMMENT='BANNER';
INSERT INTO banner(NEWS_ID)
VALUES ('1');

-- ================== CREATE TABLE(客服相關）================== --
-- 聊天室 --
CREATE TABLE chat_room(
	ROOM_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '聊天室ID',
	ROOM_URL VARCHAR(300) COMMENT '聊天室URL',
    ROOM_STATUS INT(1) NOT NULL COMMENT '聊天室狀態',
    ROOM_UPDATE_STATUS INT(1) NOT NULL COMMENT '聊天室已讀狀態',
    ROOM_LAST_UPDATE DATETIME COMMENT '聊天室最後更新時間'
) COMMENT='聊天室';
INSERT INTO chat_room (ROOM_URL,ROOM_STATUS,ROOM_UPDATE_STATUS,ROOM_LAST_UPDATE)
VALUES('chatRoomUrl',1,0,NOW());

-- 客服聊天紀錄 --
CREATE TABLE message(
	MSG_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '聊天紀錄ID',
	EMP_ID INT NOT NULL COMMENT '管理員ID',
	MEM_ID INT NOT NULL COMMENT '會員ID',
	ROOM_ID INT NOT NULL COMMENT '聊天室ID',
	MSG_CONTENT VARCHAR(3000) COMMENT '聊天內容',
	MSG_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL COMMENT '訊息時間',
	MSG_DIRECTION INT(1) NOT NULL COMMENT '發送方向(0:客服對會員 1:會員對客服)',
    MSG_PICTURE VARCHAR(300) COMMENT '聊天圖片路徑',
    MSG_IMAGE VARCHAR(100) COMMENT '聊天圖片名稱',
    CONSTRAINT message_employee_fk FOREIGN KEY (EMP_ID) REFERENCES employee(EMP_ID),
    CONSTRAINT message_member_fk FOREIGN KEY (MEM_ID) REFERENCES member(MEM_ID),
    CONSTRAINT message_chat_room_fk FOREIGN KEY (ROOM_ID) REFERENCES chat_room(ROOM_ID)
) COMMENT='客服聊天紀錄';
INSERT INTO message (EMP_ID,MEM_ID,ROOM_ID,MSG_CONTENT,MSG_DIRECTION)
VALUES (1,1,1,"HI",0),
	   (1,1,1,"Hello",0);

-- 商品分類 --
CREATE TABLE product_collection(
	PDC_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '商品分類ID',
    PDC_NAME VARCHAR(10) NOT NULL COMMENT '商品分類名稱',
    PDC_KEYWORD VARCHAR(200) COMMENT '商品分類關鍵字',
    PDC_STATUS INT(2) NOT NULL DEFAULT 1 COMMENT '商品分類狀態(0:下架 1:上架 Default:0)'
) COMMENT='商品分類';
INSERT INTO product_collection(PDC_NAME,PDC_KEYWORD)
VALUES ('可麗路','巧克力 起司 抹茶')
	  ,('可頌','巧克力 楓糖 蜂蜜 紅豆');

-- 商品 --
CREATE TABLE product(
	PD_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '商品ID',
    PDC_ID INT NOT NULL COMMENT '商品分類ID',
    PD_NAME VARCHAR(30) NOT NULL UNIQUE COMMENT '商品名稱', 
    PD_PRICE INT NOT NULL COMMENT '商品原價', 
    PD_DESCRIPTION VARCHAR(200) COMMENT '商品資訊', 
    PD_DISPLAY_QUANTITY INT COMMENT '商品圖片陳列數量', 
    PD_STATUS INT(2) NOT NULL DEFAULT 1 COMMENT '商品狀態(0:下架 1:上架 Default:0)', 
    PD_IS_DEL INT(1) NOT NULL DEFAULT 0 COMMENT '商品刪除(0:未刪除 1:刪除 Default:0)', 
    PD_CREATE_BY VARCHAR(20) COMMENT '商品創建人',
	PD_CREATE_TIME DATETIME COMMENT '商品創建時間',
	PD_UPDATE_BY VARCHAR(20) COMMENT '商品最後修改人',
	PD_UPDATE_TIME DATETIME COMMENT '商品最後修改時間',
    CONSTRAINT product_product_collection_fk FOREIGN KEY (PDC_ID) REFERENCES product_collection(PDC_ID)
) COMMENT='商品';
INSERT INTO product(PDC_ID, PD_NAME, PD_PRICE, PD_DESCRIPTION, PD_DISPLAY_QUANTITY, PD_STATUS, PD_IS_DEL, PD_CREATE_BY,PD_CREATE_TIME,PD_UPDATE_BY,PD_UPDATE_TIME)
VALUES (1, '奶茶風味可麗露', 300, '奶茶風味可麗露最好吃', 2, 1, 0,'AnthonyFu',NOW(),'AnthonyFu',NOW()),
       (1, '抹茶風味可麗露', 500, '抹茶風味可麗露最好吃', 2, 1, 0,'AnthonyFu',NOW(),'AnthonyFu',NOW());

-- 商品圖片 --
CREATE TABLE product_pic (
	PD_PIC_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '商品圖片ID',
    PD_ID INT COMMENT '商品ID',
    PD_PIC_SORT INT COMMENT '商品圖片排序',
    PD_PICTURE VARCHAR(300) COMMENT '商品圖片路徑',
    PD_IMAGE VARCHAR(100) COMMENT '商品圖片名稱',
    CONSTRAINT product_pic_product_fk FOREIGN KEY (PD_ID) REFERENCES product(PD_ID)
) COMMENT='商品圖片';
INSERT INTO product_pic(PD_ID, PD_PIC_SORT, PD_PICTURE, PD_IMAGE)
VALUES (1, 1, 'holidayDessert/admin/upload/images/productPic/20240731093732.jpg', '20240731093732.jpg'),
	   (1, 2, 'holidayDessert/admin/upload/images/productPic/20240731093732.jpg', '20240731093732.jpg'),
	   (1, 3, 'holidayDessert/admin/upload/images/productPic/20240731093732.jpg', '20240731093732.jpg'),
	   (2, 1, 'holidayDessert/admin/upload/images/productPic/20240731093746.jpg', '20240731093746.jpg'),
	   (2, 3, 'holidayDessert/admin/upload/images/productPic/20240731093746.jpg', '20240731093746.jpg'),
	   (2, 2, 'holidayDessert/admin/upload/images/productPic/20240731093746.jpg', '20240731093746.jpg');

-- ================== CREATE TABLE(優惠相關）================== --

-- 活動優惠方案 --
 CREATE TABLE promotion(
PM_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '活動優惠ID',
PM_NAME VARCHAR(45) NOT NULL COMMENT '活動名稱',
PM_DESCRIPTION VARCHAR(255) COMMENT '活動描述',
PM_DISCOUNT DECIMAL(3,2) COMMENT '折扣幅度',
PM_REGULARLY INT(1) NOT NULL COMMENT '活動例行性(0:非例行 1:例行)',
PM_STATUS INT(1) NOT NULL COMMENT '活動狀態(0:下架 1:上架)',
PM_START DATETIME COMMENT '開始時間',
PM_END DATETIME COMMENT '結束時間'
) COMMENT='活動優惠方案';
INSERT INTO promotion(PM_NAME,PM_DESCRIPTION,PM_DISCOUNT,PM_REGULARLY,PM_STATUS,PM_START,PM_END)
VALUES('單品特價','特價商品最優惠',1.00,1,1,null,null),
	  ('中秋節特價','全館79折',0.79,1,1,CONCAT(CURDATE(), ' 00:00:00'),CONCAT(DATE_ADD(CURDATE(), INTERVAL 1 WEEK), ' 23:59:59'));

-- 優惠活動明細 --
CREATE TABLE promotion_detail(
PMD_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '活動優惠明細ID',
PD_ID INT NOT NULL COMMENT '商品ID',
PM_ID INT NOT NULL COMMENT '活動優惠ID',
PMD_START DATETIME COMMENT '起始時間',
PMD_END DATETIME COMMENT '截止時間',
PMD_PD_DISCOUNT_PRICE INT COMMENT '商品活動優惠價',
CONSTRAINT promotion_detail_promotion_fk FOREIGN KEY (PM_ID) REFERENCES promotion(PM_ID),
CONSTRAINT promotion_detail_product_fk FOREIGN KEY (PD_ID) REFERENCES product(PD_ID)
) COMMENT='優惠活動明細';
INSERT INTO promotion_detail(PM_ID,PD_ID,PMD_START,PMD_END,PMD_PD_DISCOUNT_PRICE)
VALUES(2,1,CONCAT(CURDATE(), ' 00:00:00'), str_to_date('2022-08-31','%Y-%m-%d'),237);

-- 優惠券種類 --
CREATE TABLE coupon(
	CP_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '優惠券種類ID',
    CP_NAME VARCHAR(45) NOT NULL COMMENT '優惠券名稱',
    CP_DISCOUNT INT NOT NULL COMMENT '優惠券折扣價格',
    CP_STATUS INT(1) NOT NULL COMMENT '優惠券狀態(0:下架 1:上架)',
    CP_PICTURE VARCHAR(300) COMMENT '優惠券圖片路徑',
    CP_IMAGE VARCHAR(100) COMMENT '優惠券圖片名稱'
) COMMENT='優惠券種類';
INSERT INTO coupon(CP_NAME, CP_DISCOUNT, CP_STATUS)
VALUES ('50元購物金', 50, 1),
       ('10元折價券', 10, 0);
       
-- 會員優惠券 --
CREATE TABLE member_coupon(
	MEM_CP_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '會員優惠券ID',
    MEM_ID INT NOT NULL COMMENT '會員ID',
    CP_ID INT NOT NULL COMMENT '優惠券種類ID',
    MEM_CP_START DATETIME NOT NULL COMMENT '起始時間',
    MEM_CP_END DATETIME NOT NULL COMMENT '截止時間',
    MEM_CP_STATUS INT(1) NOT NULL COMMENT '使用狀態(0:不可用 1:可用)',
    MEM_CP_RECORD DATETIME COMMENT '使用紀錄',
    CONSTRAINT member_coupon_member_fk FOREIGN KEY (MEM_ID) REFERENCES member(MEM_ID),
    CONSTRAINT member_coupon_coupon_fk FOREIGN KEY (CP_ID) REFERENCES coupon(CP_ID)
) COMMENT='會員優惠券';
INSERT INTO member_coupon(MEM_ID, CP_ID, MEM_CP_START,MEM_CP_END, MEM_CP_STATUS, MEM_CP_RECORD)
VALUES (1, 1, CONCAT(CURDATE(), ' 00:00:00'),str_to_date('2022-10-31','%Y-%m-%d'), 1, null);

-- ================== CREATE TABLE(商品相關）================== --

-- 購物車-- 
CREATE TABLE cart(
	MEM_ID int NOT NULL COMMENT '會員ID',
    PD_ID int NOT NULL COMMENT '商品ID',
    CART_PD_QUANTITY int NOT NULL COMMENT '商品個數',
    CONSTRAINT cart_member_fk FOREIGN KEY (MEM_ID) REFERENCES member(MEM_ID),
    CONSTRAINT cart_product_fk FOREIGN KEY (PD_ID) REFERENCES product(PD_ID),
    PRIMARY KEY(MEM_ID, PD_ID)
) COMMENT='購物車';
INSERT INTO cart(MEM_ID, PD_ID, CART_PD_QUANTITY)
VALUES (1, 1, 3);

-- 訂單 --
CREATE TABLE main_order(
	ORD_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '訂單ID',
    MEM_ID INT NOT NULL COMMENT '會員ID',
    MEM_CP_ID INT COMMENT '會員優惠券ID',
    ORD_SUBTOTAL INT NOT NULL COMMENT '小計(未扣cupon折扣)',
    ORD_TOTAL INT NOT NULL COMMENT '總計(扣除cupon折扣)',
    ORD_STATUS INT(1) NOT NULL DEFAULT 0 COMMENT '訂單狀態(0:未完成 1:已完成 2:配送中 3:取消)(預設 0)',
    ORD_CREATE DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '訂單成立時間',
    ORD_RECIPIENT VARCHAR(20) NOT NULL COMMENT '收件人',
    ORD_RECIPIENT_PHONE VARCHAR(20) NOT NULL COMMENT '收件人連絡電話',
    ORD_PAYMENT INT(2) NOT NULL COMMENT '付款方式(0:貨到付款 1:信用卡)',
    ORD_DELIVERY INT(2) NOT NULL COMMENT '送貨方式(0:超商取貨 1:宅配)',
    ORD_ADDRESS VARCHAR(100) NOT NULL COMMENT '收件地址',
    ORD_NOTE VARCHAR(100) COMMENT '訂單備註',
    ORD_DELIVERY_FEE INT NOT NULL COMMENT '運費',
    CONSTRAINT main_order_member_fk FOREIGN KEY (MEM_ID) REFERENCES member(MEM_ID),
    CONSTRAINT main_order_member_coupon_fk FOREIGN KEY (MEM_CP_ID) REFERENCES member_coupon(MEM_CP_ID)
) COMMENT='訂單';
INSERT INTO main_order(MEM_ID, MEM_CP_ID, ORD_SUBTOTAL, ORD_TOTAL, ORD_RECIPIENT, ORD_RECIPIENT_PHONE, ORD_PAYMENT, ORD_DELIVERY, ORD_DELIVERY_FEE ,ORD_ADDRESS)
VALUES (1, null, 270, 270, 'leoblue', '0987654321', 1, 1,'100', '桃園');
       
-- 訂單明細 --
CREATE TABLE order_detail(
	ORD_ID INT NOT NULL COMMENT '訂單ID',
    PD_ID INT NOT NULL COMMENT '商品ID',
    ORDD_NUMBER INT NOT NULL COMMENT '商品個數',
    ORDD_PRICE INT NOT NULL COMMENT '商品單價',
    ORDD_DISCOUNT_PRICE INT NOT NULL COMMENT '商品活動優惠單價',
    CONSTRAINT order_detail_main_order_fk FOREIGN KEY (ORD_ID) REFERENCES main_order(ORD_ID),
    CONSTRAINT order_detail_product_fk FOREIGN KEY (PD_ID) REFERENCES product(PD_ID),
	PRIMARY KEY(ORD_ID, PD_ID)
) COMMENT='訂單明細';
INSERT INTO order_detail(ORD_ID, PD_ID, ORDD_NUMBER, ORDD_PRICE, ORDD_DISCOUNT_PRICE)
VALUES (1, 1, 3, 300, 270);

-- 公司資訊 --
CREATE TABLE company_information(
	COM_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '公司資訊ID',
    COM_NAME VARCHAR(45) NOT NULL COMMENT '店鋪名稱',
    COM_ADDRESS VARCHAR(45) NOT NULL COMMENT '店鋪地址',
    COM_PHONE VARCHAR(20) NOT NULL COMMENT '店鋪電話',
    COM_MEMO VARCHAR(500) NOT NULL COMMENT '店鋪詳細資訊'
) COMMENT='公司資訊';
INSERT INTO company_information(COM_NAME, COM_ADDRESS, COM_PHONE, COM_MEMO)
VALUES ('假日甜點', '桃園市楊梅區甡甡路646號', '0981023222', '享受假日時光');

-- 表單 --
CREATE TABLE form(
FORM_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '送單ID',
FORM_PHONE VARCHAR(20) COMMENT '送單人電話',
FORM_EMAIL VARCHAR(40) NOT NULL COMMENT '送單人信箱',
FORM_CONTENT VARCHAR(500) COMMENT '送單內容',
FORM_CREATE_BY VARCHAR(50) COMMENT '送單人',
FORM_CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '送單創建時間'
) COMMENT='表單';
INSERT INTO form(FORM_PHONE,FORM_EMAIL,FORM_CONTENT,FORM_CREATE_BY)
VALUES ('0911064756','s9017611@gmail.com','我想購買 怎麼聯繫您們','傅勝宏'),
	   ('0911064756','s9017688@gmail.com','我想購買','AnthonyFuFu');
       
-- 留言 --
CREATE TABLE `comment`(
CMT_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '留言ID',
MEM_ID int NOT NULL COMMENT '留言人ID',
CMT_STATUS INT(2) NOT NULL default 1 COMMENT '是否顯示留言',
CMT_CHECK INT(1) NOT NULL default 0 COMMENT '留言是否被確認',
CMT_PICTURE VARCHAR(300) COMMENT '留言人圖片',
CMT_CONTENT VARCHAR(500) COMMENT '留言內容',
CMT_CREATE_BY VARCHAR(50) COMMENT '留言創建人',
CMT_CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) COMMENT='留言';
INSERT INTO `comment`(MEM_ID,CMT_CONTENT,CMT_CREATE_BY)
VALUES (1,'只屬於你的快樂時光，請你和我們一起悠閒品嘗。','傅勝宏'),
	   (2,'只屬於你的快樂時光，請你和我們一起悠閒品嘗。只屬於你的快樂時光，請你和我們一起悠閒品嘗。只屬於你的快樂時光，請你和我們一起悠閒品嘗。','AnthonyFuFu'),
	   (3,'只屬於你的快樂時光，請你和我們一起悠閒品嘗。只屬於你的快樂時光，請你和我們一起悠閒品嘗。只屬於你的快樂時光，請你和我們一起悠閒品嘗。','AnthonyFu');

-- 操作紀錄 --
CREATE TABLE edit_log(
LOG_ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '操作紀錄ID',
LOG_IP VARCHAR(50) COMMENT '操作紀錄IP',
LOG_URL VARCHAR(50) COMMENT '操作紀錄URL',
LOG_TYPE VARCHAR(20) COMMENT '操作紀錄前/後台',
LOG_METHOD VARCHAR(50) COMMENT '操作紀錄請求方法',
LOG_HTTP_STATUS_CODE VARCHAR(50) COMMENT '操作紀錄狀態碼',
LOG_CONTENT LONGTEXT COMMENT '操作紀錄內容',
LOG_CREATE_BY VARCHAR(50) COMMENT '操作紀錄創建人',
LOG_CREATE_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '操作紀錄創建時間'
) COMMENT='操作紀錄';
INSERT INTO edit_log(LOG_IP,LOG_URL,LOG_TYPE,LOG_METHOD,LOG_HTTP_STATUS_CODE,LOG_CONTENT,LOG_CREATE_BY)
VALUES ('0:0:0:0:0:0:0:1','/form/sendForm','employee','POST',200,'{"mem_name":["傅勝宏"],"form_content":["我想購買 怎麼聯繫您們"]}',"傅勝宏"),
	   ('0:0:0:0:0:0:0:1','/form/sendForm','member','POST',200,'{"mem_name":["傅勝宏"],"form_content":["我想購買 怎麼聯繫您們"]}',"傅勝宏");

-- 排班管理 --
CREATE TABLE fullcalendar (
    id INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT '唯一的事件 ID',
    title VARCHAR(255) NOT NULL COMMENT '事件的標題',
    start DATETIME NOT NULL COMMENT '事件的開始日期/時間',
    end DATETIME DEFAULT NULL COMMENT '事件的結束日期/時間',
    allDay INT(1) NOT NULL DEFAULT 0 COMMENT '是否為全天事件',
    url VARCHAR(2083) DEFAULT NULL COMMENT '點擊事件後開啟的連結',
    classNames VARCHAR(5000) DEFAULT NULL COMMENT '自訂的 CSS 類別名稱',
    editable INT(1) NOT NULL DEFAULT 0 COMMENT '是否允許該事件被拖動或調整大小',
    startEditable INT(1) NOT NULL DEFAULT 0 COMMENT '是否允許調整事件開始時間',
    durationEditable INT(1) NOT NULL DEFAULT 0 COMMENT '是否允許改變事件的持續時間',
    overlap INT(1) NOT NULL DEFAULT 1 COMMENT '是否允許事件重疊',
    display ENUM('auto', 'block', 'list-item', 'background', 'inverse-background', 'none') DEFAULT 'auto' COMMENT '事件的顯示方式',
    backgroundColor VARCHAR(7) DEFAULT NULL COMMENT '背景顏色',
    borderColor VARCHAR(7) DEFAULT NULL COMMENT '邊框顏色',
    textColor VARCHAR(7) DEFAULT NULL COMMENT '文字顏色',
    groupId VARCHAR(255) DEFAULT NULL COMMENT '群組 ID，用於將多個事件歸為同一群組',
    extendedProps VARCHAR(5000) DEFAULT NULL COMMENT '自訂屬性',
    isApproved INT(1) NOT NULL DEFAULT 0 COMMENT '是否已審核 (由管理員控制)',
    EMP_ID INT DEFAULT NULL COMMENT '事件擁有者 ID，對應 employee 表的 EMP_ID',
    CONSTRAINT calendar_employee_fk FOREIGN KEY (EMP_ID) REFERENCES employee(EMP_ID) ON DELETE CASCADE
) COMMENT='排班管理';
INSERT INTO fullcalendar (title, start, end, allDay, backgroundColor, borderColor,EMP_ID)
VALUES('Meeting', CONCAT(CURDATE(), ' 10:00:00'), CONCAT(DATE_ADD(CURDATE(), INTERVAL 1 WEEK), ' 12:00:00'), 0, '#f56954', '#f56954',1),
      ('Conference', CONCAT(DATE_ADD(CURDATE(), INTERVAL 2 DAY), ' 09:00:00'), CONCAT(DATE_ADD(CURDATE(), INTERVAL 1 WEEK), ' 17:00:00'), 0, '#00a65a', '#00a65a',2),
      ('Lunch', CONCAT(CURDATE(), ' 12:00:00'), CONCAT(DATE_ADD(CURDATE(), INTERVAL 2 WEEK), ' 13:00:00'), 0, '#f39c12', '#f39c12',2),
      ('Multi-day Event with Time', CONCAT(DATE_ADD(CURDATE(), INTERVAL 1 WEEK), ' 14:00:00'), CONCAT(DATE_ADD(CURDATE(), INTERVAL 3 WEEK), ' 16:00:00'), 0, '#0073b7', '#0073b7',2),
      ('Conference2', CONCAT(DATE_ADD(CURDATE(), INTERVAL 2 DAY), ' 09:00:00'), CONCAT(DATE_ADD(CURDATE(), INTERVAL 1 WEEK), ' 17:00:00'), 0, '#00a65a', '#00a65a',3),
      ('Lunch2', CONCAT(CURDATE(), ' 12:00:00'), CONCAT(DATE_ADD(CURDATE(), INTERVAL 2 WEEK), ' 13:00:00'), 0, '#f39c12', '#f39c12',3),
      ('Multi-day Event with Time2', CONCAT(DATE_ADD(CURDATE(), INTERVAL 1 WEEK), ' 14:00:00'), CONCAT(DATE_ADD(CURDATE(), INTERVAL 3 WEEK), ' 16:00:00'), 0, '#0073b7', '#0073b7',3);
      
-- 活動資料表
CREATE TABLE ticket (
    TICKET_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '活動 ID，自動遞增',
    TICKET_NAME VARCHAR(100) NOT NULL UNIQUE COMMENT '活動名稱',
    TICKET_START DATETIME NOT NULL COMMENT '活動開始時間',
    TICKET_SALE_START DATETIME NOT NULL COMMENT '售票開始時間',
    TICKET_SALE_END DATETIME NOT NULL COMMENT '售票結束時間',
    TICKET_QUANTITY INT NOT NULL COMMENT '總票數',
    TICKET_STATUS INT(2) NOT NULL DEFAULT 1 COMMENT '活動狀態(0:尚未開始 1:開始期間 2:活動結束 3:活動取消)',
    TICKET_CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '建立時間',
    TICKET_UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新時間'
) COMMENT='票務活動資料表';

INSERT INTO ticket (TICKET_NAME, TICKET_START, TICKET_SALE_START, TICKET_SALE_END, TICKET_QUANTITY, TICKET_STATUS)
VALUES ('五月天演唱會', '2025-07-10 19:00:00', CONCAT(CURDATE(), ' 10:00:00'), CONCAT(DATE_ADD(CURDATE(), INTERVAL 1 WEEK), ' 23:59:59'), 1000, 1),
       ('小巨蛋動漫展', '2025-08-05 10:00:00', CONCAT(CURDATE(), ' 09:00:00'), CONCAT(DATE_ADD(CURDATE(), INTERVAL 1 WEEK), ' 23:59:59'), 800, 2),
       ('跨年煙火派對', '2025-12-31 22:00:00', CONCAT(CURDATE(), ' 12:00:00'), CONCAT(DATE_ADD(CURDATE(), INTERVAL 1 WEEK), ' 23:59:59'), 2000, 0);

-- 票種資料表
CREATE TABLE ticket_type (
    TYPE_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '票種 ID',
    TICKET_ID INT NOT NULL COMMENT '對應活動 ID',
    TYPE_NAME VARCHAR(100) NOT NULL COMMENT '票種名稱 / 區域 / 價格說明',
    TYPE_PRICE INT NOT NULL COMMENT '票價',
    TYPE_QUANTITY INT NOT NULL COMMENT '可售張數',
    TYPE_CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '建立時間',
    TYPE_UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新時間',
    CONSTRAINT ticket_type_ticket_FK FOREIGN KEY (TICKET_ID) REFERENCES ticket(TICKET_ID)
) COMMENT='票種資料表';
INSERT INTO ticket_type (TICKET_ID, TYPE_NAME, TYPE_PRICE, TYPE_QUANTITY)
VALUES (1, '搖滾區', 3200, 100),(1, '看台區', 1800, 300),(1, '一般票', 350, 250),(1, '免費票', 0, 500),
	   (2, '搖滾區', 3200, 100),(2, '看台區', 1800, 300),(2, '一般票', 350, 250),(2, '免費票', 0, 500),
       (3, '搖滾區', 3200, 100),(3, '看台區', 1800, 300),(3, '一般票', 350, 250),(3, '免費票', 0, 500);

-- 訂單資料表
CREATE TABLE ticket_order (
    TICKET_ORD_ID INT AUTO_INCREMENT PRIMARY KEY COMMENT '訂單 ID',
    MEM_ID INT NOT NULL COMMENT '會員 ID',
    TYPE_ID INT NOT NULL COMMENT '票種 ID',
    TICKET_ORD_QUANTITY INT NOT NULL COMMENT '購買張數',
    TICKET_ORD_STATUS INT(2) NOT NULL DEFAULT 0 COMMENT '訂單狀態(0:待辦 1:完成)',
    TICKET_ORD_TIME DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '下單時間',
    CONSTRAINT ticket_order_member_FK FOREIGN KEY (MEM_ID) REFERENCES member(MEM_ID),
    CONSTRAINT ticket_order_ticket_type_FK FOREIGN KEY (TYPE_ID) REFERENCES ticket_type(TYPE_ID)
) COMMENT='訂單資料表';
INSERT INTO ticket_order (MEM_ID, TYPE_ID, TICKET_ORD_QUANTITY, TICKET_ORD_STATUS)
VALUES (1, 1, 2, 1),
       (2, 3, 1, 0);
