input {
        stdin {

        }
        jdbc {
                # mysql 資料庫連接
                jdbc_connection_string => "jdbc:mysql://localhost:3306/holiday_dessert"
                # 帳號密碼
                jdbc_user => "admin"
                jdbc_password => "admin"
                # 修改為mysql檔案位置
                jdbc_driver_library => "/root/jdbc/mysql-connector-java-8.0.31.jar"
                # Driver 名稱
                jdbc_driver_class => "com.mysql.cj.jdbc.Driver"
                jdbc_paging_enabled => "true"
                jdbc_page_size => "50000"
                # SQL的位置，SQL也可以直接寫在下方。
                statement => "SELECT * FROM holiday_dessert.v_member"
                # 設定監聽時間間隔 各位置意涵（由左至右）分、時、天、月、年，全部*默認代表每分鐘更新
                schedule => "*/2 * * * *"
                type => "index_member"
        }

}
filter {
        mutate {
                copy => {"mem_id" => "[@metadata][mem_id]"}
        }
}
output {
        if[type] == "index_member"  {
        opensearch {
        # ES的IP地址及端口
            hosts => ["http://localhost:9200"]
                # index 可自行定義
                index => "index_member"
		document_id => "%{mem_id}"
                user => "admin"
                password => "admin"
		cacert => ""
        }
     }
}
